### ISSUE TITLE
Project status ...

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/docker-maker#1]
Hi--wondering if you are working on this project currently, and/or need assistance with strategy, documentation, or the like. LMK! -- Lauri

**Comment by dryewo** [comment]
Hi! This projects is to be deprecated in favor of https://github.com/zalando/pazuzu-cli and https://github.com/zalando/pazuzu-registry

**Comment by LappleApple** [comment]
Got it. Should we deprecate or delete completely? If it's not going to be of use to the community, I'd vote for the latter.

**Comment by dryewo** [comment]
I can make it private not to confuse the community, but some code examples from it can be useful for the team working on Pazuzu

**Comment by LappleApple** [comment]
Sounds like a good plan.
